call npm install -g d3
call npm install -g jsdom
call npm install -g restify
call npm install -g commander
call npm install -g request
call npm install -g pn
call npm install -g phantom
call npm install -g node-telegram-bot-api
call npm install -g stream-buffers